apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  interval: 15m
  chart:
    spec:
      chart: eck-operator
      version: "3.x.x"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  install:
    createNamespace: true
  values:
    # Example minimal dev values
    managedNamespaces: []
