apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres
  namespace: postgres
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: "18.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  values:
    # Generic base values
    architecture: standalone
