apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: logstash
      version: "8.x.x"
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  install:
    createNamespace: true
