apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redpanda
  namespace: kafka
spec:
  interval: 15m
  chart:
    spec:
      chart: redpanda
      version: "26.x.x"
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: flux-system
  install:
    createNamespace: true
  values:
    # Example minimal dev values
    statefulset:
      replicas: 1
    resources:
      cpu:
        cores: 1
      memory:
        container:
          max: 2Gi
