apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 15m
  chart:
    spec:
      chart: vault
      version: "0.34.x"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    createNamespace: true
  values:
    # Example minimal dev values
    server:
      dev:
        enabled: true
