apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-obi
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: opentelemetry-ebpf-instrumentation
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  install:
    createNamespace: true
  values:
    # Example minimal dev values
    cluster_name: "example-cluster"
