apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-databases
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/example-cluster-01/databases
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cluster-infrastructure
