apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: databases
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: "19.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    createNamespace: true
  values:
    # Generic base values
    architecture: standalone
